### ISSUE TITLE
Inconsistency between pycore and cpp bindings

### ISSUE THREAD

**Issue by delwen** [G-Node/nixpy#262]
An analysis that works with the cpp bindings does not work with pycore:

```sh
│ ├─ Tags: ap1 Traceback (most recent call last):
  File "./ca-analyse.py", line 455, in <module>
    main()
  File "./ca-analyse.py", line 448, in main
    analyser.process()
  File "./ca-analyse.py", line 189, in process
    self.process_file(path)
  File "./ca-analyse.py", line 215, in process_file
    self.process_neuron(neuron)
  File "./ca-analyse.py", line 268, in process_neuron
    data = np.array([mtag.retrieve_data(pc, 0)[0] for pc in range(len(p))])
  File "/usr/local/lib/python2.7/site-packages/nixio/pycore/multi_tag.py", line 155, in retrieve_data
    offset, count = self._get_offset_and_count(ref, posidx)
  File "/usr/local/lib/python2.7/site-packages/nixio/pycore/multi_tag.py", line 112, in _get_offset_and_count
    offsets.append(self._pos_to_idx(offset[idx], unit, dim))
  File "/usr/local/lib/python2.7/site-packages/nixio/pycore/tag.py", line 145, in _pos_to_idx
    dimunit = dim.unit
AttributeError: 'SetDimension' object has no attribute 'unit'
```

**Comment by delwen** [comment]
Analysis script is in [gicmo/CaAnalysis](https://github.com/gicmo/CaAnalysis).

**Comment by delwen** [comment]
Applying to PR 263 and testing again now leads to:
```
  File "./ca-analyse.py", line 455, in <module>
    main()
  File "./ca-analyse.py", line 448, in main
    analyser.process()
  File "./ca-analyse.py", line 189, in process
    self.process_file(path)
  File "./ca-analyse.py", line 215, in process_file
    self.process_neuron(neuron)
  File "./ca-analyse.py", line 268, in process_neuron
    data = np.array([mtag.retrieve_data(pc, 0)[0] for pc in range(len(p))])
  File "/usr/local/lib/python2.7/site-packages/nixio-1.3.1-py2.7-macosx-10.12-x86_64.egg/nixio/pycore/multi_tag.py", line 156, in retrieve_data
    if not self._position_and_extent_in_data(ref, offset, count):
  File "/usr/local/lib/python2.7/site-packages/nixio-1.3.1-py2.7-macosx-10.12-x86_64.egg/nixio/pycore/tag.py", line 133, in _position_and_extent_in_data
    pos = tuple(np.add(offset, count) - 1)
ValueError: operands could not be broadcast together with shapes (2,) (0,)
```
